-- Tabel pentru fișele de caz (intervenții Salvamont).
-- Rulați o singură dată în phpMyAdmin, pe baza de date a aplicației.
CREATE TABLE IF NOT EXISTS case_sheets (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nr_fisa VARCHAR(50) NOT NULL DEFAULT '',
    data_fisa DATE NULL,
    judet VARCHAR(100) NOT NULL DEFAULT '',
    serviciu VARCHAR(150) NOT NULL DEFAULT '',
    formatie VARCHAR(150) NOT NULL DEFAULT '',
    alarmare_prin VARCHAR(150) NOT NULL DEFAULT '',
    alarmare_data DATE NULL,
    alarmare_ora TIME NULL,
    tip_eveniment VARCHAR(150) NOT NULL DEFAULT '',
    responsabilitate VARCHAR(150) NOT NULL DEFAULT '',
    interventie VARCHAR(150) NOT NULL DEFAULT '',
    coordonator VARCHAR(150) NOT NULL DEFAULT '',
    salvatori TEXT NULL,
    locatie_judet VARCHAR(100) NOT NULL DEFAULT '',
    masiv_montan VARCHAR(150) NOT NULL DEFAULT '',
    sezon VARCHAR(20) NOT NULL DEFAULT '',
    loc_producere VARCHAR(255) NOT NULL DEFAULT '',
    tip_activitate VARCHAR(150) NOT NULL DEFAULT '',
    numar_persoane VARCHAR(20) NOT NULL DEFAULT '',
    victima_nume VARCHAR(200) NOT NULL DEFAULT '',
    victima_varsta VARCHAR(20) NOT NULL DEFAULT '',
    victima_sex VARCHAR(5) NOT NULL DEFAULT '',
    victima_judet VARCHAR(100) NOT NULL DEFAULT '',
    victima_tara VARCHAR(100) NOT NULL DEFAULT '',
    victima_stare VARCHAR(255) NOT NULL DEFAULT '',
    victima_contact VARCHAR(150) NOT NULL DEFAULT '',
    localizare_afectiune VARCHAR(255) NOT NULL DEFAULT '',
    finalitate_caz VARCHAR(255) NOT NULL DEFAULT '',
    predare_data DATE NULL,
    predare_ora TIME NULL,
    transport VARCHAR(150) NOT NULL DEFAULT '',
    mod_evacuare VARCHAR(20) NOT NULL DEFAULT '',
    predata_catre VARCHAR(200) NOT NULL DEFAULT '',
    victime_multiple VARCHAR(5) NOT NULL DEFAULT '',
    revenire_data DATE NULL,
    revenire_ora TIME NULL,
    intocmit VARCHAR(200) NOT NULL DEFAULT '',
    created_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_created_at (created_at),
    CONSTRAINT fk_case_sheets_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
